--- #YAML:1.0
name:                Sort-Key-IPv4
version:             0.01
abstract:            sort IPv4 addresses
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.32
distribution_type:   module
requires:     
    Sort::Key:                     1.28
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Salvador Fandino <sfandino@yahoo.com>
